version: '3'

services:
  jenkins:
    image: alejandro945/jenkins-with-sshpass:latest
    container_name: jenkins
    ports:
      - "8080:8080"
    environment:
      - DISPLAY=IP_de_tu_PC_con_servidor_X11:0
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always

volumes:
  jenkins_home:
